import { useState } from 'react'
import PageHeading from '../components/PageHeading'
import Toolbar from '../components/Toolbar'
import StatusBadge from '../components/StatusBadge'
import EmptyState from '../components/EmptyState'
import { dateLabel } from '../utils'

export default function Enquiries({ enquiries, role, onCreate, onQuote }) {
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState('All status')
  return <div><PageHeading eyebrow="SALES PIPELINE" title="Customer enquiries" description="Every great partnership starts with a conversation." action={role === 'SALES_USER' ? onCreate : null} actionLabel="New enquiry" /><div className="summary-strip"><div><span className="summary-dot dot-lavender" /><span>All enquiries</span><strong>{enquiries.length}</strong></div><div><span className="summary-dot dot-blue" /><span>New</span><strong>{enquiries.filter((entry) => entry.status === 'NEW').length}</strong></div><div><span className="summary-dot dot-orange" /><span>Quoted</span><strong>{enquiries.filter((entry) => entry.status === 'QUOTED').length}</strong></div><div><span className="summary-dot dot-green" /><span>Won</span><strong>{enquiries.filter((entry) => entry.status === 'WON').length}</strong></div></div><div className="panel listing-panel"><Toolbar search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} statuses={['NEW', 'QUOTED', 'WON', 'LOST']} placeholder="Search company, enquiry..." /><div className="table-scroll"><table><thead><tr><th>ENQUIRY</th><th>CUSTOMER</th><th>PRODUCTS</th><th>REQUIRED BY</th><th>STATUS</th><th /></tr></thead><tbody>{enquiries.filter((entry) => `${entry.id} ${entry.company} ${entry.contact} ${entry.city}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'All status' || entry.status === filter)).map((entry) => <tr key={entry.id}><td><strong className="table-primary">{entry.id}</strong><span className="table-secondary">Created {dateLabel(entry.date)}</span></td><td><strong className="table-customer">{entry.company}</strong><span className="table-secondary">{entry.contact} · {entry.city}</span></td><td><strong>{entry.products.length} product{entry.products.length !== 1 && 's'}</strong><span className="table-secondary">{entry.products.reduce((sum, item) => sum + item.quantity, 0)} units total</span></td><td>{dateLabel(entry.required)}</td><td><StatusBadge status={entry.status} /></td><td>{role === 'SALES_USER' && entry.status !== 'WON' && entry.status !== 'LOST' && <button className="row-action" onClick={() => onQuote(entry)}>Create quote <span>→</span></button>}</td></tr>)}</tbody></table>{enquiries.length === 0 && <EmptyState title="No enquiries found" text="Try changing your search or add a new enquiry." />}</div><div className="table-footer"><span>Showing <strong>{enquiries.length ? 1 : 0}–{enquiries.length}</strong> of <strong>{enquiries.length}</strong> enquiries</span><div><button disabled>←</button><button className="current-page">1</button><button disabled>→</button></div></div></div></div>
}
