import { useState } from 'react'
import PageHeading from '../components/PageHeading'
import Toolbar from '../components/Toolbar'
import { money } from '../utils'

export default function Inventory({ products, role, available, onEdit, onCreate }) {
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState('All status')
  const totalUnits = products.reduce((sum, product) => sum + available(product), 0)
  const inventoryValue = products.reduce((sum, product) => sum + product.physical * product.price, 0)
  return <div><PageHeading eyebrow="PRODUCT CATALOGUE" title="Inventory" description="Know what’s in stock, what’s reserved, and what’s ready to go." action={role === 'ADMIN' ? onCreate : null} actionLabel="Add product" /><div className="summary-strip"><div><span className="summary-dot dot-lavender" /><span>Products</span><strong>{products.length}</strong></div><div><span className="summary-dot dot-green" /><span>Available units</span><strong>{totalUnits.toLocaleString('en-IN')}</strong></div><div><span className="summary-dot dot-orange" /><span>Reserved units</span><strong>{products.reduce((sum, product) => sum + product.reserved, 0).toLocaleString('en-IN')}</strong></div><div><span className="summary-dot dot-blue" /><span>Stock value</span><strong>{money(inventoryValue)}</strong></div></div><div className="panel listing-panel"><Toolbar search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} statuses={['In stock', 'Low stock']} placeholder="Search code, product..." /><div className="table-scroll"><table><thead><tr><th>PRODUCT</th><th>CATEGORY</th><th>UNIT PRICE</th><th>PHYSICAL</th><th>RESERVED</th><th>AVAILABLE</th><th>STOCK STATUS</th>{role === 'ADMIN' && <th />}</tr></thead><tbody>{products.filter((product) => `${product.code} ${product.name} ${product.category}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'All status' || (filter === 'Low stock' ? available(product) < 100 : available(product) >= 100))).map((product) => <tr key={product.id}><td><div className="product-name-cell"><span className="product-mark">{product.code.slice(-1)}</span><span><strong className="table-customer">{product.name}</strong><small>{product.code}</small></span></div></td><td>{product.category}</td><td>{money(product.price)} <span className="table-secondary">/ {product.unit}</span></td><td>{product.physical.toLocaleString('en-IN')}</td><td>{product.reserved.toLocaleString('en-IN')}</td><td><strong>{available(product).toLocaleString('en-IN')}</strong></td><td><span className={`stock-status ${available(product) < 100 ? 'stock-low' : 'stock-ok'}`}><i />{available(product) < 100 ? 'Low stock' : 'In stock'}</span></td>{role === 'ADMIN' && <td><button className="more-row-action" aria-label={`Update ${product.name}`} onClick={() => onEdit(product)}>···</button></td>}</tr>)}</tbody></table></div><div className="inventory-note"><span>ⓘ</span> Available stock is calculated as physical quantity minus reserved quantity. Stock is reserved at order confirmation and deducted on dispatch.</div></div></div>
}
