import { useState } from 'react'
import PageHeading from '../components/PageHeading'
import Toolbar from '../components/Toolbar'
import StatusBadge from '../components/StatusBadge'
import { dateLabel, money, quoteTotal } from '../utils'

export default function Orders({ orders, role, onConfirm, onDispatch, onCancel }) {
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState('All status')
  return <div><PageHeading eyebrow="ORDER MANAGEMENT" title="Sales orders" description="From confirmation to dispatch, keep every order on track." /><div className="summary-strip"><div><span className="summary-dot dot-lavender" /><span>All orders</span><strong>{orders.length}</strong></div><div><span className="summary-dot dot-orange" /><span>Pending</span><strong>{orders.filter((order) => order.status === 'PENDING').length}</strong></div><div><span className="summary-dot dot-blue" /><span>Confirmed</span><strong>{orders.filter((order) => order.status === 'CONFIRMED').length}</strong></div><div><span className="summary-dot dot-green" /><span>Dispatched</span><strong>{orders.filter((order) => order.status === 'DISPATCHED').length}</strong></div></div><div className="panel listing-panel"><Toolbar search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} statuses={['PENDING', 'CONFIRMED', 'DISPATCHED', 'CANCELLED']} placeholder="Search order, customer..." /><div className="table-scroll"><table><thead><tr><th>SALES ORDER</th><th>CUSTOMER</th><th>QUOTE / ENQUIRY</th><th>ORDER DATE</th><th>AMOUNT</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{orders.filter((order) => `${order.id} ${order.company} ${order.quoteId}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'All status' || order.status === filter)).map((order) => <tr key={order.id}><td><strong className="table-primary">{order.id}</strong><span className="table-secondary">{order.items.length} product{order.items.length !== 1 && 's'}</span></td><td><strong className="table-customer">{order.company}</strong></td><td><strong>{order.quoteId}</strong><span className="table-secondary">{order.enquiryId}</span></td><td>{dateLabel(order.date)}</td><td><strong>{money(quoteTotal(order.items))}</strong></td><td><StatusBadge status={order.status} /></td><td className="action-cell">{role === 'ADMIN' && order.status === 'PENDING' && <><button className="row-action" onClick={() => onConfirm(order)}>Confirm <span>→</span></button><button className="icon-row-action" title="Cancel order" onClick={() => onCancel(order)}>×</button></>}{role === 'ADMIN' && order.status === 'CONFIRMED' && <><button className="row-action" onClick={() => onDispatch(order)}>Dispatch <span>→</span></button><button className="icon-row-action" title="Cancel order" onClick={() => onCancel(order)}>×</button></>}</td></tr>)}</tbody></table></div><div className="table-footer"><span>Showing <strong>{orders.length ? 1 : 0}–{orders.length}</strong> of <strong>{orders.length}</strong> sales orders</span><div><button disabled>←</button><button className="current-page">1</button><button disabled>→</button></div></div></div></div>
}
