import { useState } from 'react'
import PageHeading from '../components/PageHeading'
import Toolbar from '../components/Toolbar'
import StatusBadge from '../components/StatusBadge'
import { dateLabel, money, quoteTotal } from '../utils'

export default function Quotations({ quotes, orders, role, onCreate, onStatus, onConvert }) {
  const [search, setSearch] = useState('')
  const [filter, setFilter] = useState('All status')
  return <div><PageHeading eyebrow="PRICING & PROPOSALS" title="Quotations" description="Build clear, accurate proposals your customers can say yes to." action={role === 'SALES_USER' ? onCreate : null} actionLabel="New quotation" /><div className="summary-strip"><div><span className="summary-dot dot-lavender" /><span>Total quotations</span><strong>{quotes.length}</strong></div><div><span className="summary-dot dot-orange" /><span>Awaiting response</span><strong>{quotes.filter((quote) => quote.status === 'SENT').length}</strong></div><div><span className="summary-dot dot-green" /><span>Accepted</span><strong>{quotes.filter((quote) => quote.status === 'ACCEPTED').length}</strong></div><div><span className="summary-dot dot-red" /><span>Rejected</span><strong>{quotes.filter((quote) => quote.status === 'REJECTED').length}</strong></div></div><div className="panel listing-panel"><Toolbar search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} statuses={['DRAFT', 'SENT', 'ACCEPTED', 'REJECTED']} placeholder="Search quote, customer..." /><div className="table-scroll"><table><thead><tr><th>QUOTATION</th><th>CUSTOMER / ENQUIRY</th><th>VALID UNTIL</th><th>GRAND TOTAL</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{quotes.filter((quote) => `${quote.id} ${quote.company} ${quote.enquiryId}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'All status' || quote.status === filter)).map((quote) => <tr key={quote.id}><td><strong className="table-primary">{quote.id}</strong><span className="table-secondary">Created {dateLabel(quote.date)}</span></td><td><strong className="table-customer">{quote.company}</strong><span className="table-secondary">{quote.enquiryId} · {quote.items.length} product{quote.items.length !== 1 && 's'}</span></td><td>{dateLabel(quote.validUntil)}</td><td><strong>{money(quoteTotal(quote.items))}</strong></td><td><StatusBadge status={quote.status} /></td><td className="action-cell">{role === 'SALES_USER' && quote.status === 'DRAFT' && <button className="row-action" onClick={() => onStatus(quote, 'SENT')}>Mark sent <span>→</span></button>}{role === 'SALES_USER' && quote.status === 'SENT' && <><button className="row-action" onClick={() => onStatus(quote, 'ACCEPTED')}>Accept <span>✓</span></button><button className="icon-row-action" title="Mark rejected" onClick={() => onStatus(quote, 'REJECTED')}>×</button></>}{role === 'SALES_USER' && quote.status === 'ACCEPTED' && <button className="row-action" disabled={orders.some((order) => order.quoteId === quote.id)} onClick={() => onConvert(quote)}>{orders.some((order) => order.quoteId === quote.id) ? 'Order created' : 'Create order'} <span>→</span></button>}</td></tr>)}</tbody></table></div><div className="table-footer"><span>Showing <strong>{quotes.length ? 1 : 0}–{quotes.length}</strong> of <strong>{quotes.length}</strong> quotations</span><div><button disabled>←</button><button className="current-page">1</button><button disabled>→</button></div></div></div></div>
}
